/*Generated by concorde router generator*/
import { html } from "lit";
import "@supersoniks/concorde/core/components/functional/router/router";

import layout from "./layout";
import configAccountPage from "./config/account/page";
import configDataPage from "./config/data/page";
import configDatasetsPage from "./config/datasets/page";
import configMaintenancePage from "./config/maintenance/page";
import configP2pPage from "./config/p2p/page";
import configPage from "./config/page";
import tacheItem_idEditPage from "./tache/item/[id]/edit/page";
import tacheItem_idMovePage from "./tache/item/[id]/move/page";
import tacheItem_idNewPage from "./tache/item/[id]/new/page";
import tacheItem_idPage from "./tache/item/[id]/page";
import tacheNewPage from "./tache/new/page";
import tachePage from "./tache/page";
import tagsItem_idEditPage from "./tags/item/[id]/edit/page";
import tagsNewPage from "./tags/new/page";
import tagsPage from "./tags/page";
import page from "./page";
import fallback from "./404";
export const router = (basePath?:string) => {
const configAccountDefaultLayoutRoutes = {
    "/config/account$": configAccountPage
}        

const configDataDefaultLayoutRoutes = {
    "/config/data$": configDataPage
}        

const configDatasetsDefaultLayoutRoutes = {
    "/config/datasets$": configDatasetsPage
}        

const configMaintenanceDefaultLayoutRoutes = {
    "/config/maintenance$": configMaintenancePage
}        

const configP2pDefaultLayoutRoutes = {
    "/config/p2p$": configP2pPage
}        

const configDefaultLayoutRoutes = {
    "/config/account\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configAccountDefaultLayoutRoutes}></sonic-router>`,
    "/config/data\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configDataDefaultLayoutRoutes}></sonic-router>`,
    "/config/datasets\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configDatasetsDefaultLayoutRoutes}></sonic-router>`,
    "/config/maintenance\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configMaintenanceDefaultLayoutRoutes}></sonic-router>`,
    "/config/p2p\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configP2pDefaultLayoutRoutes}></sonic-router>`,
    "/config$": configPage
}        

const tacheItem_idEditDefaultLayoutRoutes = {
    "/tache/item/:id/edit": tacheItem_idEditPage
}        

const tacheItem_idMoveDefaultLayoutRoutes = {
    "/tache/item/:id/move": tacheItem_idMovePage
}        

const tacheItem_idNewDefaultLayoutRoutes = {
    "/tache/item/:id/new": tacheItem_idNewPage
}        

const tacheItem_idDefaultLayoutRoutes = {
    "/tache/item/:id/edit(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tacheItem_idEditDefaultLayoutRoutes}></sonic-router>`,
    "/tache/item/:id/move(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tacheItem_idMoveDefaultLayoutRoutes}></sonic-router>`,
    "/tache/item/:id/new(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tacheItem_idNewDefaultLayoutRoutes}></sonic-router>`,
    "/tache/item/:id": tacheItem_idPage
}        

const tacheItemDefaultLayoutRoutes = {
    "/tache/item/:id(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tacheItem_idDefaultLayoutRoutes}></sonic-router>`
}        

const tacheNewDefaultLayoutRoutes = {
    "/tache/new$": tacheNewPage
}        

const tacheDefaultLayoutRoutes = {
    "/tache/item\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tacheItemDefaultLayoutRoutes}></sonic-router>`,
    "/tache/new\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tacheNewDefaultLayoutRoutes}></sonic-router>`,
    "/tache$": tachePage
}        

const tagsItem_idEditDefaultLayoutRoutes = {
    "/tags/item/:id/edit": tagsItem_idEditPage
}        

const tagsItem_idDefaultLayoutRoutes = {
    "/tags/item/:id/edit(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tagsItem_idEditDefaultLayoutRoutes}></sonic-router>`
}        

const tagsItemDefaultLayoutRoutes = {
    "/tags/item/:id(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tagsItem_idDefaultLayoutRoutes}></sonic-router>`
}        

const tagsNewDefaultLayoutRoutes = {
    "/tags/new$": tagsNewPage
}        

const tagsDefaultLayoutRoutes = {
    "/tags/item\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tagsItemDefaultLayoutRoutes}></sonic-router>`,
    "/tags/new\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tagsNewDefaultLayoutRoutes}></sonic-router>`,
    "/tags$": tagsPage
}        

const layoutRoutes = {
    "/config\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configDefaultLayoutRoutes}></sonic-router>`,
    "/tache\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tacheDefaultLayoutRoutes}></sonic-router>`,
    "/tags\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tagsDefaultLayoutRoutes}></sonic-router>`,
    "/$": page,
    "fallback": fallback
}        
return layout(html`<sonic-router .basePath=${basePath} .routes=${layoutRoutes}></sonic-router>`)}