/*Generated by concorde router generator*/
import { html } from "lit";
import "@supersoniks/concorde/core/components/functional/router/router";

import layout from "./layout";
import accountPage from "./account/page";
import configAccountPage from "./config/account/page";
import configActivityPage from "./config/activity/page";
import configAppearancePage from "./config/appearance/page";
import configDataPage from "./config/data/page";
import configDatasetsPage from "./config/datasets/page";
import configIssuesPage from "./config/issues/page";
import configMaintenancePage from "./config/maintenance/page";
import configP2pPage from "./config/p2p/page";
import configUsagePage from "./config/usage/page";
import configWebhooksPage from "./config/webhooks/page";
import configPage from "./config/page";
import connectivityActivityPage from "./connectivity/activity/page";
import connectivityMcpPage from "./connectivity/mcp/page";
import connectivityUsagePage from "./connectivity/usage/page";
import connectivityWebhooksPage from "./connectivity/webhooks/page";
import dataCloudPage from "./data/cloud/page";
import dataExportPage from "./data/export/page";
import dataLocalPage from "./data/local/page";
import dataMaintenancePage from "./data/maintenance/page";
import dataP2pPage from "./data/p2p/page";
import invitePage from "./invite/page";
import settingsAppearancePage from "./settings/appearance/page";
import settingsInstallPage from "./settings/install/page";
import settingsLinksPage from "./settings/links/page";
import settingsNotificationsPage from "./settings/notifications/page";
import settingsPage from "./settings/page";
import tacheItem_idEditPage from "./tache/item/[id]/edit/page";
import tacheItem_idMovePage from "./tache/item/[id]/move/page";
import tacheItem_idNewPage from "./tache/item/[id]/new/page";
import tacheItem_idPage from "./tache/item/[id]/page";
import tacheNewPage from "./tache/new/page";
import tachePage from "./tache/page";
import tagsItem_idEditPage from "./tags/item/[id]/edit/page";
import tagsNewPage from "./tags/new/page";
import tagsPage from "./tags/page";
import page from "./page";
import fallback from "./404";
export const router = (basePath?:string) => {
const accountDefaultLayoutRoutes = {
    "/account$": accountPage
}        

const configAccountDefaultLayoutRoutes = {
    "/config/account$": configAccountPage
}        

const configActivityDefaultLayoutRoutes = {
    "/config/activity$": configActivityPage
}        

const configAppearanceDefaultLayoutRoutes = {
    "/config/appearance$": configAppearancePage
}        

const configDataDefaultLayoutRoutes = {
    "/config/data$": configDataPage
}        

const configDatasetsDefaultLayoutRoutes = {
    "/config/datasets$": configDatasetsPage
}        

const configIssuesDefaultLayoutRoutes = {
    "/config/issues$": configIssuesPage
}        

const configMaintenanceDefaultLayoutRoutes = {
    "/config/maintenance$": configMaintenancePage
}        

const configP2pDefaultLayoutRoutes = {
    "/config/p2p$": configP2pPage
}        

const configUsageDefaultLayoutRoutes = {
    "/config/usage$": configUsagePage
}        

const configWebhooksDefaultLayoutRoutes = {
    "/config/webhooks$": configWebhooksPage
}        

const configDefaultLayoutRoutes = {
    "/config/account\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configAccountDefaultLayoutRoutes}></sonic-router>`,
    "/config/activity\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configActivityDefaultLayoutRoutes}></sonic-router>`,
    "/config/appearance\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configAppearanceDefaultLayoutRoutes}></sonic-router>`,
    "/config/data\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configDataDefaultLayoutRoutes}></sonic-router>`,
    "/config/datasets\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configDatasetsDefaultLayoutRoutes}></sonic-router>`,
    "/config/issues\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configIssuesDefaultLayoutRoutes}></sonic-router>`,
    "/config/maintenance\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configMaintenanceDefaultLayoutRoutes}></sonic-router>`,
    "/config/p2p\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configP2pDefaultLayoutRoutes}></sonic-router>`,
    "/config/usage\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configUsageDefaultLayoutRoutes}></sonic-router>`,
    "/config/webhooks\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configWebhooksDefaultLayoutRoutes}></sonic-router>`,
    "/config$": configPage
}        

const connectivityActivityDefaultLayoutRoutes = {
    "/connectivity/activity$": connectivityActivityPage
}        

const connectivityMcpDefaultLayoutRoutes = {
    "/connectivity/mcp$": connectivityMcpPage
}        

const connectivityUsageDefaultLayoutRoutes = {
    "/connectivity/usage$": connectivityUsagePage
}        

const connectivityWebhooksDefaultLayoutRoutes = {
    "/connectivity/webhooks$": connectivityWebhooksPage
}        

const connectivityDefaultLayoutRoutes = {
    "/connectivity/activity\\b": () => html`<sonic-router .basePath=${basePath} .routes=${connectivityActivityDefaultLayoutRoutes}></sonic-router>`,
    "/connectivity/mcp\\b": () => html`<sonic-router .basePath=${basePath} .routes=${connectivityMcpDefaultLayoutRoutes}></sonic-router>`,
    "/connectivity/usage\\b": () => html`<sonic-router .basePath=${basePath} .routes=${connectivityUsageDefaultLayoutRoutes}></sonic-router>`,
    "/connectivity/webhooks\\b": () => html`<sonic-router .basePath=${basePath} .routes=${connectivityWebhooksDefaultLayoutRoutes}></sonic-router>`
}        

const dataCloudDefaultLayoutRoutes = {
    "/data/cloud$": dataCloudPage
}        

const dataExportDefaultLayoutRoutes = {
    "/data/export$": dataExportPage
}        

const dataLocalDefaultLayoutRoutes = {
    "/data/local$": dataLocalPage
}        

const dataMaintenanceDefaultLayoutRoutes = {
    "/data/maintenance$": dataMaintenancePage
}        

const dataP2pDefaultLayoutRoutes = {
    "/data/p2p$": dataP2pPage
}        

const dataDefaultLayoutRoutes = {
    "/data/cloud\\b": () => html`<sonic-router .basePath=${basePath} .routes=${dataCloudDefaultLayoutRoutes}></sonic-router>`,
    "/data/export\\b": () => html`<sonic-router .basePath=${basePath} .routes=${dataExportDefaultLayoutRoutes}></sonic-router>`,
    "/data/local\\b": () => html`<sonic-router .basePath=${basePath} .routes=${dataLocalDefaultLayoutRoutes}></sonic-router>`,
    "/data/maintenance\\b": () => html`<sonic-router .basePath=${basePath} .routes=${dataMaintenanceDefaultLayoutRoutes}></sonic-router>`,
    "/data/p2p\\b": () => html`<sonic-router .basePath=${basePath} .routes=${dataP2pDefaultLayoutRoutes}></sonic-router>`
}        

const inviteDefaultLayoutRoutes = {
    "/invite$": invitePage
}        

const settingsAppearanceDefaultLayoutRoutes = {
    "/settings/appearance$": settingsAppearancePage
}        

const settingsInstallDefaultLayoutRoutes = {
    "/settings/install$": settingsInstallPage
}        

const settingsLinksDefaultLayoutRoutes = {
    "/settings/links$": settingsLinksPage
}        

const settingsNotificationsDefaultLayoutRoutes = {
    "/settings/notifications$": settingsNotificationsPage
}        

const settingsDefaultLayoutRoutes = {
    "/settings/appearance\\b": () => html`<sonic-router .basePath=${basePath} .routes=${settingsAppearanceDefaultLayoutRoutes}></sonic-router>`,
    "/settings/install\\b": () => html`<sonic-router .basePath=${basePath} .routes=${settingsInstallDefaultLayoutRoutes}></sonic-router>`,
    "/settings/links\\b": () => html`<sonic-router .basePath=${basePath} .routes=${settingsLinksDefaultLayoutRoutes}></sonic-router>`,
    "/settings/notifications\\b": () => html`<sonic-router .basePath=${basePath} .routes=${settingsNotificationsDefaultLayoutRoutes}></sonic-router>`,
    "/settings$": settingsPage
}        

const tacheItem_idEditDefaultLayoutRoutes = {
    "/tache/item/:id/edit": tacheItem_idEditPage
}        

const tacheItem_idMoveDefaultLayoutRoutes = {
    "/tache/item/:id/move": tacheItem_idMovePage
}        

const tacheItem_idNewDefaultLayoutRoutes = {
    "/tache/item/:id/new": tacheItem_idNewPage
}        

const tacheItem_idDefaultLayoutRoutes = {
    "/tache/item/:id/edit(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tacheItem_idEditDefaultLayoutRoutes}></sonic-router>`,
    "/tache/item/:id/move(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tacheItem_idMoveDefaultLayoutRoutes}></sonic-router>`,
    "/tache/item/:id/new(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tacheItem_idNewDefaultLayoutRoutes}></sonic-router>`,
    "/tache/item/:id": tacheItem_idPage
}        

const tacheItemDefaultLayoutRoutes = {
    "/tache/item/:id(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tacheItem_idDefaultLayoutRoutes}></sonic-router>`
}        

const tacheNewDefaultLayoutRoutes = {
    "/tache/new$": tacheNewPage
}        

const tacheDefaultLayoutRoutes = {
    "/tache/item\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tacheItemDefaultLayoutRoutes}></sonic-router>`,
    "/tache/new\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tacheNewDefaultLayoutRoutes}></sonic-router>`,
    "/tache$": tachePage
}        

const tagsItem_idEditDefaultLayoutRoutes = {
    "/tags/item/:id/edit": tagsItem_idEditPage
}        

const tagsItem_idDefaultLayoutRoutes = {
    "/tags/item/:id/edit(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tagsItem_idEditDefaultLayoutRoutes}></sonic-router>`
}        

const tagsItemDefaultLayoutRoutes = {
    "/tags/item/:id(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tagsItem_idDefaultLayoutRoutes}></sonic-router>`
}        

const tagsNewDefaultLayoutRoutes = {
    "/tags/new$": tagsNewPage
}        

const tagsDefaultLayoutRoutes = {
    "/tags/item\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tagsItemDefaultLayoutRoutes}></sonic-router>`,
    "/tags/new\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tagsNewDefaultLayoutRoutes}></sonic-router>`,
    "/tags$": tagsPage
}        

const layoutRoutes = {
    "/account\\b": () => html`<sonic-router .basePath=${basePath} .routes=${accountDefaultLayoutRoutes}></sonic-router>`,
    "/config\\b": () => html`<sonic-router .basePath=${basePath} .routes=${configDefaultLayoutRoutes}></sonic-router>`,
    "/connectivity\\b": () => html`<sonic-router .basePath=${basePath} .routes=${connectivityDefaultLayoutRoutes}></sonic-router>`,
    "/data\\b": () => html`<sonic-router .basePath=${basePath} .routes=${dataDefaultLayoutRoutes}></sonic-router>`,
    "/invite\\b": () => html`<sonic-router .basePath=${basePath} .routes=${inviteDefaultLayoutRoutes}></sonic-router>`,
    "/settings\\b": () => html`<sonic-router .basePath=${basePath} .routes=${settingsDefaultLayoutRoutes}></sonic-router>`,
    "/tache\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tacheDefaultLayoutRoutes}></sonic-router>`,
    "/tags\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tagsDefaultLayoutRoutes}></sonic-router>`,
    "/$": page,
    "fallback": fallback
}        
return layout(html`<sonic-router .basePath=${basePath} .routes=${layoutRoutes}></sonic-router>`)}