/*Generated by concorde router generator*/
import { html } from "lit";
import "@supersoniks/concorde/core/components/functional/router/router";

import layout from "./layout";
import accountLoginPage from "./account/login/page";
import accountRegisterPage from "./account/register/page";
import accountVerifyPage from "./account/verify/page";
import accountPage from "./account/page";
import connectivityActivityPage from "./connectivity/activity/page";
import connectivityEmbedsPage from "./connectivity/embeds/page";
import connectivityMcpPage from "./connectivity/mcp/page";
import connectivityUsagePage from "./connectivity/usage/page";
import connectivityWebhooksPage from "./connectivity/webhooks/page";
import dataCloudPage from "./data/cloud/page";
import dataExportPage from "./data/export/page";
import dataLocalPage from "./data/local/page";
import dataMaintenancePage from "./data/maintenance/page";
import dataP2pPage from "./data/p2p/page";
import dataSyncPage from "./data/sync/page";
import invitePage from "./invite/page";
import settingsAppearancePage from "./settings/appearance/page";
import settingsInstallPage from "./settings/install/page";
import settingsLinksPage from "./settings/links/page";
import settingsNotificationsPage from "./settings/notifications/page";
import settingsPage from "./settings/page";
import tacheItem_idEditPage from "./tache/item/[id]/edit/page";
import tacheItem_idMovePage from "./tache/item/[id]/move/page";
import tacheItem_idNewPage from "./tache/item/[id]/new/page";
import tacheItem_idPage from "./tache/item/[id]/page";
import tacheNewPage from "./tache/new/page";
import tachePage from "./tache/page";
import tagsItem_idEditPage from "./tags/item/[id]/edit/page";
import tagsNewPage from "./tags/new/page";
import tagsPage from "./tags/page";
import page from "./page";
import fallback from "./404";
export const router = (basePath?:string) => {
const accountLoginDefaultLayoutRoutes = {
    "/account/login$": accountLoginPage
}        

const accountRegisterDefaultLayoutRoutes = {
    "/account/register$": accountRegisterPage
}        

const accountVerifyDefaultLayoutRoutes = {
    "/account/verify$": accountVerifyPage
}        

const accountDefaultLayoutRoutes = {
    "/account/login\\b": () => html`<sonic-router .basePath=${basePath} .routes=${accountLoginDefaultLayoutRoutes}></sonic-router>`,
    "/account/register\\b": () => html`<sonic-router .basePath=${basePath} .routes=${accountRegisterDefaultLayoutRoutes}></sonic-router>`,
    "/account/verify\\b": () => html`<sonic-router .basePath=${basePath} .routes=${accountVerifyDefaultLayoutRoutes}></sonic-router>`,
    "/account$": accountPage
}        

const connectivityActivityDefaultLayoutRoutes = {
    "/connectivity/activity$": connectivityActivityPage
}        

const connectivityEmbedsDefaultLayoutRoutes = {
    "/connectivity/embeds$": connectivityEmbedsPage
}        

const connectivityMcpDefaultLayoutRoutes = {
    "/connectivity/mcp$": connectivityMcpPage
}        

const connectivityUsageDefaultLayoutRoutes = {
    "/connectivity/usage$": connectivityUsagePage
}        

const connectivityWebhooksDefaultLayoutRoutes = {
    "/connectivity/webhooks$": connectivityWebhooksPage
}        

const connectivityDefaultLayoutRoutes = {
    "/connectivity/activity\\b": () => html`<sonic-router .basePath=${basePath} .routes=${connectivityActivityDefaultLayoutRoutes}></sonic-router>`,
    "/connectivity/embeds\\b": () => html`<sonic-router .basePath=${basePath} .routes=${connectivityEmbedsDefaultLayoutRoutes}></sonic-router>`,
    "/connectivity/mcp\\b": () => html`<sonic-router .basePath=${basePath} .routes=${connectivityMcpDefaultLayoutRoutes}></sonic-router>`,
    "/connectivity/usage\\b": () => html`<sonic-router .basePath=${basePath} .routes=${connectivityUsageDefaultLayoutRoutes}></sonic-router>`,
    "/connectivity/webhooks\\b": () => html`<sonic-router .basePath=${basePath} .routes=${connectivityWebhooksDefaultLayoutRoutes}></sonic-router>`
}        

const dataCloudDefaultLayoutRoutes = {
    "/data/cloud$": dataCloudPage
}        

const dataExportDefaultLayoutRoutes = {
    "/data/export$": dataExportPage
}        

const dataLocalDefaultLayoutRoutes = {
    "/data/local$": dataLocalPage
}        

const dataMaintenanceDefaultLayoutRoutes = {
    "/data/maintenance$": dataMaintenancePage
}        

const dataP2pDefaultLayoutRoutes = {
    "/data/p2p$": dataP2pPage
}        

const dataSyncDefaultLayoutRoutes = {
    "/data/sync$": dataSyncPage
}        

const dataDefaultLayoutRoutes = {
    "/data/cloud\\b": () => html`<sonic-router .basePath=${basePath} .routes=${dataCloudDefaultLayoutRoutes}></sonic-router>`,
    "/data/export\\b": () => html`<sonic-router .basePath=${basePath} .routes=${dataExportDefaultLayoutRoutes}></sonic-router>`,
    "/data/local\\b": () => html`<sonic-router .basePath=${basePath} .routes=${dataLocalDefaultLayoutRoutes}></sonic-router>`,
    "/data/maintenance\\b": () => html`<sonic-router .basePath=${basePath} .routes=${dataMaintenanceDefaultLayoutRoutes}></sonic-router>`,
    "/data/p2p\\b": () => html`<sonic-router .basePath=${basePath} .routes=${dataP2pDefaultLayoutRoutes}></sonic-router>`,
    "/data/sync\\b": () => html`<sonic-router .basePath=${basePath} .routes=${dataSyncDefaultLayoutRoutes}></sonic-router>`
}        

const inviteDefaultLayoutRoutes = {
    "/invite$": invitePage
}        

const settingsAppearanceDefaultLayoutRoutes = {
    "/settings/appearance$": settingsAppearancePage
}        

const settingsInstallDefaultLayoutRoutes = {
    "/settings/install$": settingsInstallPage
}        

const settingsLinksDefaultLayoutRoutes = {
    "/settings/links$": settingsLinksPage
}        

const settingsNotificationsDefaultLayoutRoutes = {
    "/settings/notifications$": settingsNotificationsPage
}        

const settingsDefaultLayoutRoutes = {
    "/settings/appearance\\b": () => html`<sonic-router .basePath=${basePath} .routes=${settingsAppearanceDefaultLayoutRoutes}></sonic-router>`,
    "/settings/install\\b": () => html`<sonic-router .basePath=${basePath} .routes=${settingsInstallDefaultLayoutRoutes}></sonic-router>`,
    "/settings/links\\b": () => html`<sonic-router .basePath=${basePath} .routes=${settingsLinksDefaultLayoutRoutes}></sonic-router>`,
    "/settings/notifications\\b": () => html`<sonic-router .basePath=${basePath} .routes=${settingsNotificationsDefaultLayoutRoutes}></sonic-router>`,
    "/settings$": settingsPage
}        

const tacheItem_idEditDefaultLayoutRoutes = {
    "/tache/item/:id/edit": tacheItem_idEditPage
}        

const tacheItem_idMoveDefaultLayoutRoutes = {
    "/tache/item/:id/move": tacheItem_idMovePage
}        

const tacheItem_idNewDefaultLayoutRoutes = {
    "/tache/item/:id/new": tacheItem_idNewPage
}        

const tacheItem_idDefaultLayoutRoutes = {
    "/tache/item/:id/edit(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tacheItem_idEditDefaultLayoutRoutes}></sonic-router>`,
    "/tache/item/:id/move(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tacheItem_idMoveDefaultLayoutRoutes}></sonic-router>`,
    "/tache/item/:id/new(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tacheItem_idNewDefaultLayoutRoutes}></sonic-router>`,
    "/tache/item/:id": tacheItem_idPage
}        

const tacheItemDefaultLayoutRoutes = {
    "/tache/item/:id(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tacheItem_idDefaultLayoutRoutes}></sonic-router>`
}        

const tacheNewDefaultLayoutRoutes = {
    "/tache/new$": tacheNewPage
}        

const tacheDefaultLayoutRoutes = {
    "/tache/item\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tacheItemDefaultLayoutRoutes}></sonic-router>`,
    "/tache/new\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tacheNewDefaultLayoutRoutes}></sonic-router>`,
    "/tache$": tachePage
}        

const tagsItem_idEditDefaultLayoutRoutes = {
    "/tags/item/:id/edit": tagsItem_idEditPage
}        

const tagsItem_idDefaultLayoutRoutes = {
    "/tags/item/:id/edit(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tagsItem_idEditDefaultLayoutRoutes}></sonic-router>`
}        

const tagsItemDefaultLayoutRoutes = {
    "/tags/item/:id(/*)": () => html`<sonic-router .basePath=${basePath} .routes=${tagsItem_idDefaultLayoutRoutes}></sonic-router>`
}        

const tagsNewDefaultLayoutRoutes = {
    "/tags/new$": tagsNewPage
}        

const tagsDefaultLayoutRoutes = {
    "/tags/item\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tagsItemDefaultLayoutRoutes}></sonic-router>`,
    "/tags/new\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tagsNewDefaultLayoutRoutes}></sonic-router>`,
    "/tags$": tagsPage
}        

const layoutRoutes = {
    "/account\\b": () => html`<sonic-router .basePath=${basePath} .routes=${accountDefaultLayoutRoutes}></sonic-router>`,
    "/connectivity\\b": () => html`<sonic-router .basePath=${basePath} .routes=${connectivityDefaultLayoutRoutes}></sonic-router>`,
    "/data\\b": () => html`<sonic-router .basePath=${basePath} .routes=${dataDefaultLayoutRoutes}></sonic-router>`,
    "/invite\\b": () => html`<sonic-router .basePath=${basePath} .routes=${inviteDefaultLayoutRoutes}></sonic-router>`,
    "/settings\\b": () => html`<sonic-router .basePath=${basePath} .routes=${settingsDefaultLayoutRoutes}></sonic-router>`,
    "/tache\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tacheDefaultLayoutRoutes}></sonic-router>`,
    "/tags\\b": () => html`<sonic-router .basePath=${basePath} .routes=${tagsDefaultLayoutRoutes}></sonic-router>`,
    "/$": page,
    "fallback": fallback
}        
return layout(html`<sonic-router .basePath=${basePath} .routes=${layoutRoutes}></sonic-router>`)}