import type {DbSnapshot} from "./types";

export const SEED_DATA: DbSnapshot = {
  tags: [
    {id: "tag-urgent", name: "urgent", color: "danger"},
    {id: "tag-dev", name: "dev", color: "info"},
  ],
  todos: [
    {
      id: "todo-1",
      text: "Préparer la spec — voir RM-12345",
      description: "Rédiger le périmètre v1 et les critères d’acceptation.",
      done: false,
      archived: false,
      priority: "high",
      tagIds: ["tag-urgent"],
      parentId: null,
      createdAt: "2026-01-10T09:00:00.000Z",
    },
    {
      id: "todo-2",
      text: "Revue du starter Concorde",
      done: true,
      archived: false,
      priority: "medium",
      tagIds: ["tag-dev"],
      parentId: null,
      createdAt: "2026-01-11T10:00:00.000Z",
    },
    {
      id: "todo-3",
      text: "Déployer l'outil de tâches",
      done: false,
      archived: false,
      priority: "high",
      tagIds: [],
      parentId: null,
      createdAt: "2026-01-12T11:00:00.000Z",
    },
    {
      id: "todo-sub-1",
      text: "API mock SW",
      done: true,
      archived: false,
      priority: "medium",
      tagIds: [],
      parentId: "todo-3",
      createdAt: "2026-01-12T11:00:00.000Z",
    },
    {
      id: "todo-sub-2",
      text: "UI sonic-queue",
      done: false,
      archived: false,
      priority: "medium",
      tagIds: [],
      parentId: "todo-3",
      createdAt: "2026-01-12T11:30:00.000Z",
    },
    {
      id: "todo-4",
      text: "Ancienne tâche supprimée",
      done: true,
      archived: true,
      priority: "low",
      tagIds: [],
      parentId: null,
      createdAt: "2025-12-01T08:00:00.000Z",
    },
  ],
};
