#!/usr/bin/env bash
# Interactive production installer for Tadaaa (Docker Compose).
# Run on a fresh VPS (Ubuntu 24.04+) as root or a user with docker access.
#
# Usage (from repo root):
#   bash scripts/install-prod.sh
#
# Only asks for a few values; secrets and CORS/MCP hosts are derived.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

COMPOSE=(docker compose -f compose.prod.yaml)
ENV_FILE="$ROOT/.env"
RED=$'\033[0;31m'
GRN=$'\033[0;32m'
YLW=$'\033[1;33m'
CYN=$'\033[0;36m'
BLD=$'\033[1m'
RST=$'\033[0m'

say() { printf '%s\n' "$*"; }
info() { printf '%s→%s %s\n' "$CYN" "$RST" "$*"; }
ok() { printf '%s✓%s %s\n' "$GRN" "$RST" "$*"; }
warn() { printf '%s!%s %s\n' "$YLW" "$RST" "$*"; }
die() { printf '%s✗%s %s\n' "$RED" "$RST" "$*" >&2; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing command: $1"
}

rand_hex() {
  # 32 bytes → 64 hex chars
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

escape_regex_host() {
  # turn app.example.com → app\.example\.com
  printf '%s' "$1" | sed 's/\./\\./g'
}

prompt() {
  # prompt VAR "Question" ["default"]
  local var="$1" question="$2" default="${3:-}" value
  if [[ -n "$default" ]]; then
    read -r -p "${question} [${default}]: " value || true
    value="${value:-$default}"
  else
    while true; do
      read -r -p "${question}: " value || true
      [[ -n "$value" ]] && break
      warn "This value is required."
    done
  fi
  printf -v "$var" '%s' "$value"
}

prompt_secret() {
  local var="$1" question="$2" value confirm
  while true; do
    read -r -s -p "${question}: " value || true
    echo
    [[ -n "$value" ]] || { warn "Password cannot be empty."; continue; }
    [[ ${#value} -ge 8 ]] || { warn "Use at least 8 characters."; continue; }
    read -r -s -p "Confirm password: " confirm || true
    echo
    [[ "$value" == "$confirm" ]] && break
    warn "Passwords do not match."
  done
  printf -v "$var" '%s' "$value"
}

banner() {
  say ""
  say "${BLD}Tadaaa — production installer${RST}"
  say "Repo root: $ROOT"
  say ""
  say "You will need:"
  say "  • A VPS with ports 80/443 open (Hetzner firewall / ufw)"
  say "  • DNS A records already pointing to this server:"
  say "      app.<domain>  →  this IP"
  say "      api.<domain>  →  this IP"
  say ""
}

check_dns_hint() {
  local host="$1" ip
  ip="$(curl -4 -fsS --max-time 3 https://ifconfig.me 2>/dev/null || true)"
  if [[ -z "$ip" ]]; then
    warn "Could not detect public IP — skip DNS check."
    return 0
  fi
  info "This server public IPv4 looks like: ${ip}"
  if command -v getent >/dev/null 2>&1; then
    local resolved
    resolved="$(getent ahostsv4 "$host" 2>/dev/null | awk '{print $1; exit}' || true)"
    if [[ -z "$resolved" ]]; then
      warn "DNS for ${host} does not resolve yet. Let's Encrypt may fail until DNS propagates."
    elif [[ "$resolved" != "$ip" ]]; then
      warn "${host} resolves to ${resolved}, not ${ip}. Fix DNS before expecting HTTPS."
    else
      ok "${host} resolves to this server."
    fi
  fi
}

install_docker_if_needed() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    ok "Docker + Compose available."
    return 0
  fi
  warn "Docker not found — installing via get.docker.com"
  need_cmd curl
  curl -fsSL https://get.docker.com | sh
  if [[ -n "${SUDO_USER:-}" ]]; then
    usermod -aG docker "$SUDO_USER" || true
  fi
  ok "Docker installed."
}

write_env() {
  local app_host="$1" api_host="$2" email="$3" app_secret="$4" pg_pass="$5"
  local cors
  cors="^https://$(escape_regex_host "$app_host")\$"

  cat >"$ENV_FILE" <<EOF
# Generated by scripts/install-prod.sh — DO NOT COMMIT
APP_SERVER_NAME=${app_host}
API_SERVER_NAME=${api_host}
ACME_EMAIL=${email}

APP_SECRET=${app_secret}
POSTGRES_DB=tada
POSTGRES_USER=app
POSTGRES_PASSWORD=${pg_pass}
POSTGRES_VERSION=16

CORS_ALLOW_ORIGIN=${cors}
REGISTRATION_AUTO_APPROVE=0
MCP_ALLOWED_HOSTS=${api_host}

HTTP_PORT=80
HTTPS_PORT=443
HTTP3_PORT=443
EOF
  chmod 600 "$ENV_FILE"
  ok "Wrote ${ENV_FILE}"
}

build_front() {
  local api_host="$1"
  info "Building front (VITE_API_BASE_URL=https://${api_host})…"
  # Mount ONLY apps/web so Yarn does not see the monorepo workspaces root
  # (otherwise deps hoist to /node_modules and break package.json paths + patch-package).
  rm -rf "$ROOT/node_modules" "$ROOT/yarn.lock"
  docker run --rm \
    -v "$ROOT/apps/web:/app" \
    -w /app \
    -e VITE_API_BASE_URL="https://${api_host}" \
    node:22-bookworm \
    bash -lc 'corepack enable && (yarn install --frozen-lockfile || yarn install) && yarn build'
  [[ -f "$ROOT/apps/web/dist/index.html" ]] || die "Front build failed (apps/web/dist/index.html missing)."
  ok "Front build ready."
}

compose_up() {
  info "Starting stack (build may take several minutes)…"
  "${COMPOSE[@]}" up -d --build
  ok "Containers started."
}

wait_api() {
  local api_host="$1" i
  info "Waiting for API health…"
  for i in $(seq 1 60); do
    if curl -fsS --max-time 5 "https://${api_host}/api/health" >/dev/null 2>&1; then
      ok "API healthy: https://${api_host}/api/health"
      return 0
    fi
    sleep 3
  done
  warn "API not reachable yet over HTTPS. Check DNS / logs: docker compose -f compose.prod.yaml logs -f edge php"
}

init_api() {
  local admin_email="$1" admin_pass="$2"
  info "Running migrations…"
  "${COMPOSE[@]}" exec -T php bin/console doctrine:migrations:migrate --no-interaction

  info "Ensuring JWT keys…"
  "${COMPOSE[@]}" exec -T php sh -c '
    set -e
    mkdir -p config/jwt
    if [ ! -f config/jwt/private.pem ]; then
      openssl genpkey -algorithm RSA -out config/jwt/private.pem -pkeyopt rsa_keygen_bits:4096
      openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem
      chmod 640 config/jwt/private.pem
      chmod 644 config/jwt/public.pem
    fi
  '

  info "Creating admin user…"
  if "${COMPOSE[@]}" exec -T php bin/console app:user:create \
    "$admin_email" "$admin_pass" --admin --active; then
    ok "Admin created: ${admin_email}"
  else
    warn "Admin create failed (user may already exist). Continue."
  fi
}

summary() {
  local app_host="$1" api_host="$2" admin_email="$3"
  say ""
  say "${BLD}Done.${RST}"
  say ""
  say "  Front:  ${GRN}https://${app_host}${RST}"
  say "  API:    ${GRN}https://${api_host}/api${RST}"
  say "  Health: ${GRN}https://${api_host}/api/health${RST}"
  say "  MCP:    ${GRN}https://${api_host}/mcp${RST}"
  say ""
  say "  Admin login: ${admin_email}"
  say "  In the app → Config → Cloud account → API URL = https://${api_host}"
  say ""
  say "Useful commands:"
  say "  docker compose -f compose.prod.yaml logs -f"
  say "  docker compose -f compose.prod.yaml ps"
  say ""
}

main() {
  banner
  need_cmd curl

  local domain app_host api_host email admin_email admin_pass
  local app_secret pg_pass

  prompt domain "Base domain (DNS must already point here)" ""
  # strip protocol / trailing slash if user pasted a URL
  domain="${domain#https://}"
  domain="${domain#http://}"
  domain="${domain%/}"

  app_host="app.${domain}"
  api_host="api.${domain}"
  say ""
  info "Will use:"
  say "  APP = https://${app_host}"
  say "  API = https://${api_host}"
  say ""
  read -r -p "OK? [Y/n] " confirm || true
  confirm="${confirm:-Y}"
  if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    prompt app_host "Front hostname" "$app_host"
    prompt api_host "API hostname" "$api_host"
  fi

  prompt email "Email for Let's Encrypt + notices" ""
  prompt admin_email "Admin account email" "$email"
  prompt_secret admin_pass "Admin password (min 8 chars)"

  check_dns_hint "$app_host"
  check_dns_hint "$api_host"

  app_secret="$(rand_hex)"
  pg_pass="$(rand_hex)"

  if [[ -f "$ENV_FILE" ]]; then
    warn "${ENV_FILE} already exists."
    read -r -p "Overwrite it? [y/N] " ow || true
    if [[ "$ow" =~ ^[Yy]$ ]]; then
      write_env "$app_host" "$api_host" "$email" "$app_secret" "$pg_pass"
    else
      ok "Keeping existing .env"
      # Prefer hosts already written in .env for rebuild/retry
      # shellcheck disable=SC1090
      set -a
      # shellcheck source=/dev/null
      source "$ENV_FILE"
      set +a
      app_host="${APP_SERVER_NAME:-$app_host}"
      api_host="${API_SERVER_NAME:-$api_host}"
    fi
  else
    write_env "$app_host" "$api_host" "$email" "$app_secret" "$pg_pass"
  fi

  install_docker_if_needed
  need_cmd docker

  build_front "$api_host"
  compose_up
  sleep 5
  init_api "$admin_email" "$admin_pass"
  wait_api "$api_host"
  summary "$app_host" "$api_host" "$admin_email"
}

main "$@"
