#!/usr/bin/env bash
# Interactive production installer for Tadaaa (Docker Compose).
# Run on a fresh VPS (Ubuntu 24.04+) as root or a user with docker access.
#
# Usage (from repo root):
#   bash scripts/install-prod.sh
#
# Asks for domain, emails, admin password, and optional Infomaniak SMTP.
# Secrets, CORS/MCP hosts, quotas defaults, build, migrate, JWT, admin are derived.
#
# Later updates: bash scripts/update-prod.sh [--pull]

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# shellcheck source=lib/prod-env.sh
source "$ROOT/scripts/lib/prod-env.sh"

COMPOSE=(docker compose -f compose.prod.yaml)
ENV_FILE="$ROOT/.env"

rand_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

escape_regex_host() {
  printf '%s' "$1" | sed 's/\./\\./g'
}

prompt() {
  local var="$1" question="$2" default="${3:-}" value
  if [[ -n "$default" ]]; then
    read -r -p "${question} [${default}]: " value || true
    value="${value:-$default}"
  else
    while true; do
      read -r -p "${question}: " value || true
      [[ -n "$value" ]] && break
      warn "This value is required."
    done
  fi
  printf -v "$var" '%s' "$value"
}

prompt_secret() {
  local var="$1" question="$2" value confirm
  while true; do
    read -r -s -p "${question}: " value || true
    echo
    [[ -n "$value" ]] || { warn "Password cannot be empty."; continue; }
    [[ ${#value} -ge 8 ]] || { warn "Use at least 8 characters."; continue; }
    read -r -s -p "Confirm password: " confirm || true
    echo
    [[ "$value" == "$confirm" ]] && break
    warn "Passwords do not match."
  done
  printf -v "$var" '%s' "$value"
}

banner() {
  say ""
  say "${BLD}Tadaaa — production installer${RST}"
  say "Repo root: $ROOT"
  say ""
  say "You will need:"
  say "  • A VPS with ports 80/443 open (Hetzner firewall / ufw)"
  say "  • DNS A records already pointing to this server:"
  say "      app.<domain>  →  this IP"
  say "      api.<domain>  →  this IP"
  say "  • Optional: Infomaniak mailbox SMTP (email verification / admin notices)"
  say ""
}

check_dns_hint() {
  local host="$1" ip
  ip="$(curl -4 -fsS --max-time 3 https://ifconfig.me 2>/dev/null || true)"
  if [[ -z "$ip" ]]; then
    warn "Could not detect public IP — skip DNS check."
    return 0
  fi
  info "This server public IPv4 looks like: ${ip}"
  if command -v getent >/dev/null 2>&1; then
    local resolved
    resolved="$(getent ahostsv4 "$host" 2>/dev/null | awk '{print $1; exit}' || true)"
    if [[ -z "$resolved" ]]; then
      warn "DNS for ${host} does not resolve yet. Let's Encrypt may fail until DNS propagates."
    elif [[ "$resolved" != "$ip" ]]; then
      warn "${host} resolves to ${resolved}, not ${ip}. Fix DNS before expecting HTTPS."
    else
      ok "${host} resolves to this server."
    fi
  fi
}

install_docker_if_needed() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    ok "Docker + Compose available."
    return 0
  fi
  warn "Docker not found — installing via get.docker.com"
  need_cmd curl
  curl -fsSL https://get.docker.com | sh
  if [[ -n "${SUDO_USER:-}" ]]; then
    usermod -aG docker "$SUDO_USER" || true
  fi
  ok "Docker installed."
}

# Args: app_host api_host acme_email app_secret pg_pass mercure_secret vapid_pub vapid_priv mail_from mailer_dsn
write_env() {
  local app_host="$1" api_host="$2" email="$3" app_secret="$4" pg_pass="$5" mercure_secret="$6"
  local vapid_public="$7" vapid_private="$8" mail_from="$9" mailer_dsn="${10}"
  local cors
  cors="^https://$(escape_regex_host "$app_host")\$"

  cat >"$ENV_FILE" <<EOF
# Generated by scripts/install-prod.sh — DO NOT COMMIT
APP_SERVER_NAME=${app_host}
API_SERVER_NAME=${api_host}
ACME_EMAIL=${email}

APP_SECRET=${app_secret}
POSTGRES_DB=tada
POSTGRES_USER=app
POSTGRES_PASSWORD=${pg_pass}
POSTGRES_VERSION=16

CORS_ALLOW_ORIGIN=${cors}
REGISTRATION_AUTO_APPROVE=0
MCP_ALLOWED_HOSTS=${api_host}

MERCURE_JWT_SECRET=${mercure_secret}
MERCURE_PUBLIC_URL=https://${api_host}/.well-known/mercure
VAPID_PUBLIC_KEY=${vapid_public}
VAPID_PRIVATE_KEY=${vapid_private}
VAPID_SUBJECT=mailto:${email}

# Transactional mail (Infomaniak SMTP) — required for signup verification
MAILER_DSN=${mailer_dsn}
MAIL_FROM=${mail_from}
APP_PUBLIC_URL=https://${app_host}

# Google Calendar OAuth (optional — set in Google Cloud Console)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# Free-tier quotas (override per user later via admin API)
DEFAULT_STORAGE_QUOTA_BYTES=5242880
GLOBAL_MONTHLY_TRANSFER_BYTES=5368709120
FLOOR_PER_USER_MONTH_BYTES=52428800
CEIL_PER_USER_MONTH_BYTES=524288000
FLOOR_PER_USER_DAY_BYTES=2097152
CEIL_PER_USER_DAY_BYTES=26214400

HTTP_PORT=80
HTTPS_PORT=443
HTTP3_PORT=443
EOF
  chmod 600 "$ENV_FILE"
  ok "Wrote ${ENV_FILE}"
}

prompt_mail_config() {
  # sets MAIL_FROM_OUT and MAILER_DSN_OUT
  local domain_hint="$1" default_from="$2"
  local mail_from smtp_user smtp_pass configure

  prompt mail_from "From address for transactional mail (MAIL_FROM)" "$default_from"
  MAIL_FROM_OUT="$mail_from"

  say ""
  say "Email verification needs SMTP (e.g. Infomaniak mail.infomaniak.com:587)."
  read -r -p "Configure Infomaniak SMTP now? [Y/n] " configure || true
  configure="${configure:-Y}"
  if [[ ! "$configure" =~ ^[Yy]$ ]]; then
    MAILER_DSN_OUT="null://null"
    warn "MAILER_DSN left as null://null — set it in .env before opening registration."
    return 0
  fi

  need_cmd python3
  prompt smtp_user "SMTP username (full mailbox email)" "$mail_from"
  prompt_secret smtp_pass "SMTP password (mailbox / app password)"
  MAILER_DSN_OUT="$(build_infomaniak_dsn "$smtp_user" "$smtp_pass")"
  ok "MAILER_DSN set for Infomaniak."
}

build_front() {
  local api_host="$1"
  info "Building front (VITE_API_BASE_URL=https://${api_host})…"
  rm -rf "$ROOT/node_modules" "$ROOT/yarn.lock"
  docker run --rm \
    -v "$ROOT/apps/web:/app" \
    -w /app \
    -e VITE_API_BASE_URL="https://${api_host}" \
    node:22-bookworm \
    bash -lc 'corepack enable && (yarn install --frozen-lockfile || yarn install) && yarn build'
  [[ -f "$ROOT/apps/web/dist/index.html" ]] || die "Front build failed (apps/web/dist/index.html missing)."
  ok "Front build ready."
}

compose_up() {
  info "Starting stack (build may take several minutes)…"
  "${COMPOSE[@]}" up -d --build
  ok "Containers started."
}

wait_api() {
  local api_host="$1" i
  info "Waiting for API health…"
  for i in $(seq 1 60); do
    if curl -fsS --max-time 5 "https://${api_host}/api/health" >/dev/null 2>&1; then
      ok "API healthy: https://${api_host}/api/health"
      return 0
    fi
    sleep 3
  done
  warn "API not reachable yet over HTTPS. Check DNS / logs: docker compose -f compose.prod.yaml logs -f edge php"
}

init_api() {
  local admin_email="$1" admin_pass="$2"
  info "Running migrations…"
  "${COMPOSE[@]}" exec -T php bin/console doctrine:migrations:migrate --no-interaction

  info "Ensuring JWT keys…"
  "${COMPOSE[@]}" exec -T php sh -c '
    set -e
    mkdir -p config/jwt
    if [ ! -f config/jwt/private.pem ]; then
      openssl genpkey -algorithm RSA -out config/jwt/private.pem -pkeyopt rsa_keygen_bits:4096
      openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem
      chmod 640 config/jwt/private.pem
      chmod 644 config/jwt/public.pem
    fi
  '

  info "Ensuring VAPID keys for Web Push…"
  if ! grep -q '^VAPID_PUBLIC_KEY=.\+' "$ENV_FILE" 2>/dev/null; then
    local vapid_json vapid_pub vapid_priv
    vapid_json="$("${COMPOSE[@]}" exec -T php php -r 'require "vendor/autoload.php"; echo json_encode(Minishlink\WebPush\VAPID::createVapidKeys());')"
    vapid_pub="$(printf '%s' "$vapid_json" | sed -n 's/.*"publicKey":"\([^"]*\)".*/\1/p')"
    vapid_priv="$(printf '%s' "$vapid_json" | sed -n 's/.*"privateKey":"\([^"]*\)".*/\1/p')"
    if [[ -n "$vapid_pub" && -n "$vapid_priv" ]]; then
      if grep -q '^VAPID_PUBLIC_KEY=' "$ENV_FILE"; then
        sed -i "s|^VAPID_PUBLIC_KEY=.*|VAPID_PUBLIC_KEY=${vapid_pub}|" "$ENV_FILE"
        sed -i "s|^VAPID_PRIVATE_KEY=.*|VAPID_PRIVATE_KEY=${vapid_priv}|" "$ENV_FILE"
      else
        printf '\nVAPID_PUBLIC_KEY=%s\nVAPID_PRIVATE_KEY=%s\nVAPID_SUBJECT=mailto:noreply@tadaaa.app\n' \
          "$vapid_pub" "$vapid_priv" >>"$ENV_FILE"
      fi
      "${COMPOSE[@]}" up -d php >/dev/null
      ok "VAPID keys written to .env"
    else
      warn "Could not generate VAPID keys — server push disabled until set manually."
    fi
  fi

  info "Creating admin user…"
  if "${COMPOSE[@]}" exec -T php bin/console app:user:create \
    "$admin_email" "$admin_pass" --admin --active; then
    ok "Admin created: ${admin_email}"
  else
    warn "Admin create failed (user may already exist). Continue."
  fi
}

summary() {
  local app_host="$1" api_host="$2" admin_email="$3" mailer_dsn="$4"
  say ""
  say "${BLD}Done.${RST}"
  say ""
  say "  Front:  ${GRN}https://${app_host}${RST}"
  say "  API:    ${GRN}https://${api_host}/api${RST}"
  say "  Health: ${GRN}https://${api_host}/api/health${RST}"
  say "  MCP:    ${GRN}https://${api_host}/mcp${RST}"
  say ""
  say "  Admin login: ${admin_email}"
  say "  In the app → Account → API URL = https://${api_host}"
  say "  Sign-up: email confirmation (APP_PUBLIC_URL=https://${app_host})"
  if [[ "$mailer_dsn" == "null://null" ]]; then
    warn "MAILER_DSN is null — configure SMTP in .env then: docker compose -f compose.prod.yaml up -d php"
  else
    ok "SMTP configured (verification / moderation emails)."
  fi
  say "  Free-tier quotas: 5 MiB storage + dynamic bandwidth (see .env)"
  say ""
  say "Later updates:"
  say "  bash scripts/update-prod.sh --pull"
  say ""
  say "Useful commands:"
  say "  docker compose -f compose.prod.yaml logs -f"
  say "  docker compose -f compose.prod.yaml ps"
  say ""
}

main() {
  banner
  need_cmd curl

  local domain app_host api_host email admin_email admin_pass
  local app_secret pg_pass mercure_secret
  local vapid_public="" vapid_private=""
  local MAIL_FROM_OUT MAILER_DSN_OUT
  local default_mail_from

  prompt domain "Base domain (DNS must already point here)" ""
  domain="${domain#https://}"
  domain="${domain#http://}"
  domain="${domain%/}"

  app_host="app.${domain}"
  api_host="api.${domain}"
  say ""
  info "Will use:"
  say "  APP = https://${app_host}"
  say "  API = https://${api_host}"
  say ""
  read -r -p "OK? [Y/n] " confirm || true
  confirm="${confirm:-Y}"
  if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    prompt app_host "Front hostname" "$app_host"
    prompt api_host "API hostname" "$api_host"
  fi

  prompt email "Email for Let's Encrypt + notices" ""
  prompt admin_email "Admin account email" "$email"
  prompt_secret admin_pass "Admin password (min 8 chars)"

  default_mail_from="app@${domain}"
  prompt_mail_config "$domain" "$default_mail_from"

  check_dns_hint "$app_host"
  check_dns_hint "$api_host"

  app_secret="$(rand_hex)"
  pg_pass="$(rand_hex)"
  mercure_secret="$(rand_hex)"

  if [[ -f "$ENV_FILE" ]]; then
    warn "${ENV_FILE} already exists."
    read -r -p "Overwrite it? [y/N] " ow || true
    if [[ "$ow" =~ ^[Yy]$ ]]; then
      write_env "$app_host" "$api_host" "$email" "$app_secret" "$pg_pass" "$mercure_secret" \
        "$vapid_public" "$vapid_private" "$MAIL_FROM_OUT" "$MAILER_DSN_OUT"
    else
      ok "Keeping existing .env — merging missing mail/quota keys…"
      set -a
      # shellcheck source=/dev/null
      source "$ENV_FILE"
      set +a
      app_host="${APP_SERVER_NAME:-$app_host}"
      api_host="${API_SERVER_NAME:-$api_host}"
      ensure_prod_env_defaults "$app_host" "$api_host" "${ACME_EMAIL:-$email}"
      # If SMTP was just configured and .env still has null, offer to write it
      if [[ "$MAILER_DSN_OUT" != "null://null" ]]; then
        if grep -qE '^MAILER_DSN=null://null$' "$ENV_FILE" 2>/dev/null || ! grep -qE '^MAILER_DSN=.' "$ENV_FILE" 2>/dev/null; then
          sed -i "s|^MAILER_DSN=.*|MAILER_DSN=${MAILER_DSN_OUT}|" "$ENV_FILE" 2>/dev/null \
            || printf '\nMAILER_DSN=%s\n' "$MAILER_DSN_OUT" >>"$ENV_FILE"
          sed -i "s|^MAIL_FROM=.*|MAIL_FROM=${MAIL_FROM_OUT}|" "$ENV_FILE" 2>/dev/null \
            || printf '\nMAIL_FROM=%s\n' "$MAIL_FROM_OUT" >>"$ENV_FILE"
          ok "Updated MAILER_DSN / MAIL_FROM in existing .env"
        fi
      fi
      set -a
      # shellcheck source=/dev/null
      source "$ENV_FILE"
      set +a
      MAILER_DSN_OUT="${MAILER_DSN:-null://null}"
    fi
  else
    write_env "$app_host" "$api_host" "$email" "$app_secret" "$pg_pass" "$mercure_secret" \
      "$vapid_public" "$vapid_private" "$MAIL_FROM_OUT" "$MAILER_DSN_OUT"
  fi

  install_docker_if_needed
  need_cmd docker

  build_front "$api_host"
  compose_up
  sleep 5
  init_api "$admin_email" "$admin_pass"
  wait_api "$api_host"
  summary "$app_host" "$api_host" "$admin_email" "$MAILER_DSN_OUT"
}

main "$@"
